# Learning how to Solve a Linear Problem using Neural Networks in PyTorch

Import basic data types

In [59]:
import pandas as pd
import numpy  as np

By building our own GMRES function, we can take it appart and play with it's insides

In [60]:
from src_dir.gmres         import GMRES, matmul_a, mat_to_a
from src_dir.nn_collection import TwoLayerNet
from src_dir.nn_predictor  import nn_preconditioner

Pyplot should display images inline

In [61]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


Work with paths...

In [62]:
from os.path import join

Import image IO libraries -- might not be needed, but I'll keep it in here or now

In [63]:
from skimage.io          import imread
import matplotlib.pyplot as     pp

Creates the validation set

In [64]:
from sklearn.model_selection import train_test_split

Evaluates the model

In [65]:
from sklearn.metrics import accuracy_score
from tqdm            import tqdm, trange

Pytorch Libraries

In [66]:
import torch
from torch.autograd import Variable
from torch.nn       import Linear, ReLU, CrossEntropyLoss, \
                           Sequential, Conv2d, MaxPool2d,  \
                           Module, Softmax, BatchNorm2d, Dropout
from torch.optim    import Adam, SGD

In [67]:
A = np.matrix(
    [[1, 1], 
     [3, -4]]
)

In [68]:
xt = np.array([2,1])
b  = matmul_a(A, xt)
x0 = np.array([0, 0])

In [69]:
b

array([3, 2])

In [70]:
e = 0
nmax_iter = 5

In [71]:
x = GMRES(A, b, x0, e, nmax_iter)

In [72]:
x

[array([3, 2]), array([1.96153846, 1.30769231]), array([2., 1.])]

In [73]:
x=torch.empty(0, 2)
y=torch.randn(1, 2)

In [74]:
x

tensor([], size=(0, 2))

In [75]:
y[0, :]

tensor([-1.0972, -0.5366])

In [76]:
z = torch.cat((x, y), 0)
z

tensor([[-1.0972, -0.5366]])

In [77]:
torch.cat((z, y), 0)

tensor([[-1.0972, -0.5366],
        [-1.0972, -0.5366]])

In [78]:
x = GMRES(A, b, x0, e, nmax_iter)

In [79]:
x

[array([3, 2]), array([1.96153846, 1.30769231]), array([2., 1.])]

In [80]:
@nn_preconditioner(retrain_freq=2, debug=True)
def MLGMRES(A, b, x0, e, nmax_iter):
    return GMRES(A, b, x0, e, nmax_iter)

In [81]:
b1 = np.array([3., 2.])
MLGMRES(A, b1, x0, e, nmax_iter)

[array([3., 2.]), array([1.96153846, 1.30769231]), array([2., 1.])]

In [82]:
b2 = np.array([3.1, 2.1])
MLGMRES(A, b2, x0, e, nmax_iter)

retraining


[array([3.1, 2.1]),
 array([2.00470377, 1.35802513]),
 array([2.07142857, 1.02857143])]

In [83]:
b3 = np.array([3.2, 2.0])
MLGMRES(A, b3, x0, e, nmax_iter)

[array([0.03048832, 0.10636806]),
 array([2.07433118, 1.0622452 ]),
 array([2.11428571, 1.08571429])]

In [84]:
b4 = np.array([3.2, 1.9])
MLGMRES(A, b4, x0, e, nmax_iter)

retraining


[array([0.03511662, 0.14372292]),
 array([2.05088798, 1.07063828]),
 array([2.1, 1.1])]

In [85]:
b5 = np.array([2.2, 2.0])
MLGMRES(A, b5, x0, e, nmax_iter)

[array([-0.1559162 , -0.38095117]),
 array([1.72176772, 0.75602093]),
 array([1.54285714, 0.65714286])]

In [86]:
b6 = np.array([0.2, 2.0])
MLGMRES(A, b6, x0, e, nmax_iter)

retraining


[array([-0.8558148 ,  0.71955097]),
 array([0.8958915, 0.1773815]),
 array([ 0.4, -0.2])]

In [87]:
b7 = np.array([3.2, 4.0])
MLGMRES(A, b7, x0, e, nmax_iter)

[array([ 0.29637308, -0.72807264]),
 array([2.27602299, 0.71300684]),
 array([2.4, 0.8])]

In [88]:
b8 = np.array([3.3, 2.0])
MLGMRES(A, b8, x0, e, nmax_iter)

retraining


[array([-0.02402194,  0.16289425]),
 array([2.16724772, 1.12577074]),
 array([2.17142857, 1.12857143])]

In [89]:
b9 = np.array([5.2, 2.0])
MLGMRES(A, b9, x0, e, nmax_iter)

[array([-0.03171067,  0.37698913]),
 array([3.22866338, 1.92404404]),
 array([3.25714286, 1.94285714])]

In [90]:
b10 = np.array([4.2, 1.0])
MLGMRES(A, b10, x0, e, nmax_iter)

retraining


[array([-0.04920762, -0.17728877]),
 array([2.60816887, 1.695657  ]),
 array([2.54285714, 1.65714286])]

In [91]:
b10 = np.array([4.2, 1.0])
MLGMRES(A, b10, x0, e, nmax_iter)

[array([ 0.00070102, -0.26077914]),
 array([2.57954591, 1.68089934]),
 array([2.54285714, 1.65714286])]

In [92]:
b10 = np.array([4.2, 1.0])
MLGMRES(A, b10, x0, e, nmax_iter)

retraining


[array([ 0.00070102, -0.26077914]),
 array([2.57954591, 1.68089934]),
 array([2.54285714, 1.65714286])]

In [93]:
MLGMRES.predictor.counter

12

In [94]:
# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 100, 2, 100, 2

# Create random Tensors to hold inputs and outputs
x = torch.randn(N, D_in)   # equivalent to b  -- in the context of Ax = b
y = torch.empty(N, D_out)  # equivalent to x  ----------- ~~ ------------
for i in range(N):
    y[i, :] = torch.from_numpy(matmul_a(A, x[i, :]))

# Construct our model by instantiating the class defined above
model = TwoLayerNet(D_in, H, D_out)

# Construct our loss function and an Optimizer. The call to model.parameters()
# in the SGD constructor will contain the learnable parameters of the two
# nn.Linear modules which are members of the model.
criterion = torch.nn.MSELoss(reduction='sum')
optimizer = torch.optim.SGD(model.parameters(), lr=1e-4)

n_steps = 10000
print_f = n_steps/100
with tqdm(total=n_steps, file=sys.stdout, leave=True) as pbar:
    for t in range(n_steps):
        # Forward pass: Compute predicted y by passing x to the model
        y_pred = model(x)

        # Compute and print loss
        loss = criterion(y_pred, y)
        if t % print_f == 0:
            # print(t, loss.item())
            loss_val = loss.item()
            pbar.set_description(f"t={t:6d}, loss={loss_val:.5f}")

        # Zero gradients, perform a backward pass, and update the weights.
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        pbar.update(1)

t=  9900, loss=0.03224: 100%|██████████| 10000/10000 [00:04<00:00, 2374.68it/s]


In [95]:
np.dot(A,x[0,:])

matrix([[-0.72728243,  2.57684015]])

In [96]:
model.forward(x[0,:])

tensor([-0.7287,  2.5746], grad_fn=<AddBackward0>)

In [97]:
y[0,:]

tensor([-0.7273,  2.5768])

In [98]:
x[0,:]

tensor([-0.0475, -0.6798])