# Learning how to Solve a Linear Problem using Neural Networks in PyTorch

Import basic data types

In [1]:
import pandas as pd
import numpy  as np

By building our own GMRES function, we can take it appart and play with it's insides

In [2]:
from src_dir         import *

Pyplot should display images inline

In [3]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


Work with paths...

In [4]:
from os.path import join

Import image IO libraries -- might not be needed, but I'll keep it in here or now

In [5]:
from skimage.io          import imread
import matplotlib.pyplot as     pp

Creates the validation set

In [6]:
from sklearn.model_selection import train_test_split

Evaluates the model

In [7]:
from sklearn.metrics import accuracy_score
from tqdm            import tqdm, trange

Pytorch Libraries

In [8]:
import torch
from torch.autograd import Variable
from torch.nn       import Linear, ReLU, CrossEntropyLoss, \
                           Sequential, Conv2d, MaxPool2d,  \
                           Module, Softmax, BatchNorm2d, Dropout
from torch.optim    import Adam, SGD

In [9]:
A = np.matrix(
    [[1, 1], 
     [3, -4]]
)

In [10]:
xt = np.array([2,1])
b  = matmul_a(A, xt)
x0 = np.array([0, 0])

In [11]:
b

array([3, 2])

In [12]:
e = 0
nmax_iter = 5

In [13]:
x = GMRES(A, b, x0, e, nmax_iter)

In [14]:
x

[array([3, 2]), array([1.96153846, 1.30769231]), array([2., 1.])]

In [15]:
x=torch.empty(0, 2)
y=torch.randn(1, 2)

In [16]:
x

tensor([], size=(0, 2))

In [17]:
y[0, :]

tensor([-0.7487, -0.9444])

In [18]:
z = torch.cat((x, y), 0)
z

tensor([[-0.7487, -0.9444]])

In [19]:
torch.cat((z, y), 0)

tensor([[-0.7487, -0.9444],
        [-0.7487, -0.9444]])

In [20]:
x = GMRES(A, b, x0, e, nmax_iter)

In [21]:
x

[array([3, 2]), array([1.96153846, 1.30769231]), array([2., 1.])]

In [22]:
@nn_preconditioner(retrain_freq=2, debug=True,InputDim=2,HiddenDim=100,OutputDim=2)
def MLGMRES(A, b, x0, e, nmax_iter):
    return GMRES(A, b, x0, e, nmax_iter)

In [23]:
b1 = np.array([3., 2.])
MLGMRES(A, b1, x0, e, nmax_iter)

[array([3., 2.]), array([1.96153846, 1.30769231]), array([2., 1.])]

In [24]:
b2 = np.array([3.1, 2.1])
MLGMRES(A, b2, x0, e, nmax_iter)

retraining


[array([3.1, 2.1]),
 array([2.00470377, 1.35802513]),
 array([2.07142857, 1.02857143])]

In [25]:
b3 = np.array([3.2, 2.0])
MLGMRES(A, b3, x0, e, nmax_iter)

[array([ 0.05736668, -0.18781185]),
 array([2.09640111, 1.07336853]),
 array([2.11428571, 1.08571429])]

In [26]:
b4 = np.array([3.2, 1.9])
MLGMRES(A, b4, x0, e, nmax_iter)

retraining


[array([ 0.08863897, -0.32215796]),
 array([2.07666546, 1.08397713]),
 array([2.1, 1.1])]

In [27]:
b5 = np.array([2.2, 2.0])
MLGMRES(A, b5, x0, e, nmax_iter)

[array([-0.31822221,  0.76349616]),
 array([1.67826992, 0.75229963]),
 array([1.54285714, 0.65714286])]

In [28]:
b6 = np.array([0.2, 2.0])
MLGMRES(A, b6, x0, e, nmax_iter)

retraining


[array([-1.17568986,  2.55004096]),
 array([0.93374715, 0.17750212]),
 array([ 0.4, -0.2])]

In [29]:
b7 = np.array([3.2, 4.0])
MLGMRES(A, b7, x0, e, nmax_iter)

[array([0.07233549, 1.03914738]),
 array([2.19288966, 0.66854713]),
 array([2.4, 0.8])]

In [30]:
b8 = np.array([3.3, 2.0])
MLGMRES(A, b8, x0, e, nmax_iter)

retraining


[array([-0.00077565, -0.03177881]),
 array([2.17659539, 1.13189294]),
 array([2.17142857, 1.12857143])]

In [31]:
b9 = np.array([5.2, 2.0])
MLGMRES(A, b9, x0, e, nmax_iter)

[array([0.01898415, 0.13135004]),
 array([3.22292831, 1.92164325]),
 array([3.25714286, 1.94285714])]

In [32]:
b10 = np.array([4.2, 1.0])
MLGMRES(A, b10, x0, e, nmax_iter)

retraining


[array([ 0.08418925, -0.08350039]),
 array([2.49470717, 1.62100563]),
 array([2.54285714, 1.65714286])]

In [33]:
b10 = np.array([4.2, 1.0])
MLGMRES(A, b10, x0, e, nmax_iter)

[array([ 0.03818316, -0.04928923]),
 array([2.52188293, 1.64173626]),
 array([2.54285714, 1.65714286])]

In [34]:
b10 = np.array([4.2, 1.0])
MLGMRES(A, b10, x0, e, nmax_iter)

retraining


[array([ 0.03818316, -0.04928923]),
 array([2.52188293, 1.64173626]),
 array([2.54285714, 1.65714286])]

In [35]:
MLGMRES.predictor.counter

12

In [36]:
# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 100, 2, 100, 2

# Create random Tensors to hold inputs and outputs
x = torch.randn(N, D_in)   # equivalent to b  -- in the context of Ax = b
y = torch.empty(N, D_out)  # equivalent to x  ----------- ~~ ------------
for i in range(N):
    y[i, :] = torch.from_numpy(matmul_a(A, x[i, :]))

# Construct our model by instantiating the class defined above
model = TwoLayerNet(D_in, H, D_out)

# Construct our loss function and an Optimizer. The call to model.parameters()
# in the SGD constructor will contain the learnable parameters of the two
# nn.Linear modules which are members of the model.
criterion = torch.nn.MSELoss(reduction='sum')
optimizer = torch.optim.SGD(model.parameters(), lr=1e-4)

n_steps = 10000
print_f = n_steps/100
with tqdm(total=n_steps, file=sys.stdout, leave=True) as pbar:
    for t in range(n_steps):
        # Forward pass: Compute predicted y by passing x to the model
        y_pred = model(x)

        # Compute and print loss
        loss = criterion(y_pred, y)
        if t % print_f == 0:
            # print(t, loss.item())
            loss_val = loss.item()
            pbar.set_description(f"t={t:6d}, loss={loss_val:.5f}")

        # Zero gradients, perform a backward pass, and update the weights.
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        pbar.update(1)

t=  9900, loss=0.03992: 100%|██████████| 10000/10000 [00:03<00:00, 2616.27it/s]


In [37]:
np.dot(A,x[0,:])

matrix([[-0.14745751,  1.71819636]])

In [38]:
model.forward(x[0,:])

tensor([-0.1476,  1.7152], grad_fn=<AddBackward0>)

In [39]:
y[0,:]

tensor([-0.1475,  1.7182])

In [40]:
x[0,:]

tensor([ 0.1612, -0.3087])