# Learning how to Solve a Linear Problem using Neural Networks in PyTorch

Import basic data types

In [1]:
import pandas as pd
import numpy  as np

By building our own GMRES function, we can take it appart and play with it's insides

In [2]:
from gmres import GMRES

Pyplot should display images inline

In [3]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


Work with paths...

In [4]:
from os.path import join

Import image IO libraries -- might not be needed, but I'll keep it in here or now

In [5]:
from skimage.io          import imread
import matplotlib.pyplot as     pp

Creates the validation set

In [6]:
from sklearn.model_selection import train_test_split

Evaluates the model

In [7]:
from sklearn.metrics import accuracy_score
from tqdm            import tqdm

Pytorch Libraries

In [8]:
import torch
from torch.autograd import Variable
from torch.nn       import Linear, ReLU, CrossEntropyLoss, \
                           Sequential, Conv2d, MaxPool2d,  \
                           Module, Softmax, BatchNorm2d, Dropout
from torch.optim    import Adam, SGD

In [19]:
matmul_a = lambda a, b : np.squeeze(np.asarray(np.dot(a, b)))

In [10]:
A = np.matrix(
    [[1, 1], 
     [3, -4]]
)

In [13]:
xt = np.array([2,1])
b  = matmul_a(A, xt)
x0 = np.array([0, 0])

In [14]:
b

array([3, 2])

In [15]:
e = 0
nmax_iter = 5

In [16]:
x = GMRES(A, b, x0, e, nmax_iter)

In [17]:
x

[array([3, 2]), array([1.96153846, 1.30769231]), array([2., 1.])]

In [145]:
train_x = list()
train_b = list()
for i in range(10000):
    train_x.append(np.array([10*randn(), 10*randn()]))
    train_b.append(matmul_a(A, train_x[-1]))

In [146]:
class TwoLayerNet(torch.nn.Module):
    def __init__(self, D_in, H, D_out):
        """
        In the constructor we instantiate two nn.Linear modules and assign them as
        member variables.
        """
        super(TwoLayerNet, self).__init__()
        self.linear1 = torch.nn.Linear(D_in, H)
        self.linear2 = torch.nn.Linear(H, D_out)

    def forward(self, x):
        """
        In the forward function we accept a Tensor of input data and we must return
        a Tensor of output data. We can use Modules defined in the constructor as
        well as arbitrary operators on Tensors.
        """
        h_relu = self.linear1(x).clamp(min=0)
        y_pred = self.linear2(h_relu)
        return y_pred


In [149]:
# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 100, 2, 100, 2

# Create random Tensors to hold inputs and outputs
x = torch.randn(N, D_in)
y = torch.randn(N, D_out)
# HACK data into here
for i in range(N):
    for j in range(D_in):
        x[i,j] = train_b[i][j]
        y[i,j] = train_x[i][j]

# Construct our model by instantiating the class defined above
model = TwoLayerNet(D_in, H, D_out)

# Construct our model by instantiating the class defined above
model = TwoLayerNet(D_in, H, D_out)

# Construct our loss function and an Optimizer. The call to model.parameters()
# in the SGD constructor will contain the learnable parameters of the two
# nn.Linear modules which are members of the model.
criterion = torch.nn.MSELoss(reduction='sum')
optimizer = torch.optim.SGD(model.parameters(), lr=1e-6)
for t in range(100000):
    # Forward pass: Compute predicted y by passing x to the model
    y_pred = model(x)

    # Compute and print loss
    loss = criterion(y_pred, y)
    if t % 100 == 99:
        print(t, loss.item())

    # Zero gradients, perform a backward pass, and update the weights.
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

99 9.566693305969238
199 6.843203067779541
299 5.268144130706787
399 4.306750774383545
499 3.7076404094696045
599 3.303642511367798
699 3.0174918174743652
799 2.8053057193756104
899 2.6193981170654297
999 2.4695656299591064
1099 2.3437352180480957
1199 2.232341766357422
1299 2.135211229324341
1399 2.0487678050994873
1499 1.9710659980773926
1599 1.9009640216827393
1699 1.8368960618972778
1799 1.7780035734176636
1899 1.7235970497131348
1999 1.6731212139129639
2099 1.6261155605316162
2199 1.5822051763534546
2299 1.54104483127594
2399 1.502371907234192
2499 1.4659407138824463
2599 1.431508183479309
2699 1.398910641670227
2799 1.367996096611023
2899 1.3386045694351196
2999 1.3106063604354858
3099 1.2839267253875732
3199 1.258463740348816
3299 1.2340848445892334
3399 1.2106443643569946
3499 1.188127875328064
3599 1.1664869785308838
3699 1.1456536054611206
3799 1.1255888938903809
3899 1.1062361001968384
3999 1.0875511169433594
4099 1.0695158243179321
4199 1.0521233081817627
4299 1.03528404235

In [150]:
model.forward(x[1,:])

tensor([7.6929, 3.9116], grad_fn=<AddBackward0>)

In [151]:
y[1,:]

tensor([7.6692, 3.9125])